import { z } from "zod";
import type { MobileAccount } from "../domain/mobile-account.js";
import type { RegisterableTool, ToolDeps, ToolResult } from "./types.js";

function apiAccount(deps: ToolDeps): MobileAccount {
  if (!deps.mobileAccount) throw new Error("mobile API account tools are not configured");
  return deps.mobileAccount;
}
function result(value: unknown): ToolResult {
  return { content: [{ type: "text", text: JSON.stringify(value, null, 2) }], structuredContent: value as Record<string, unknown> };
}
const jsonObject = z.record(z.string(), z.unknown());

export function createAccountTools(deps: ToolDeps): RegisterableTool[] {
  const authDiscovery: RegisterableTool = { name: "alza_auth_discovery", register(server, wrap) {
    server.registerTool("alza_auth_discovery", { title: "Read Alza OAuth discovery", description: "Read the live OpenID Connect discovery document used by the mobile app. This is read-only and never submits credentials.", inputSchema: {}, annotations: { readOnlyHint: true, idempotentHint: true } }, async () => wrap("alza_auth_discovery", async () => result(await apiAccount(deps).authDiscovery())));
  }};
  const authStart: RegisterableTool = { name: "alza_auth_start", register(server, wrap) {
    server.registerTool("alza_auth_start", { title: "Start Alza mobile API OAuth", description: "Create an OAuth 2.0 PKCE authorization URL for the Alza mobile API. Open the returned URL outside this MCP, complete Alza authentication, then call alza_auth_exchange with the returned code and state. No credentials enter the MCP.", inputSchema: {}, annotations: { readOnlyHint: false, idempotentHint: true } }, async () => wrap("alza_auth_start", async () => result(await apiAccount(deps).authStart())));
  }};
  const authExchange: RegisterableTool = { name: "alza_auth_exchange", register(server, wrap) {
    server.registerTool("alza_auth_exchange", { title: "Exchange Alza OAuth code", description: "Exchange the authorization code returned to alza://identity for mobile API tokens. Pass only the code and state; never pass a password or refresh token here.", inputSchema: { code: z.string().min(1), state: z.string().min(1) }, annotations: { readOnlyHint: false, idempotentHint: true } }, async (args) => wrap("alza_auth_exchange", async () => result(await apiAccount(deps).authExchange(args.code, args.state))));
  }};
  const mobileRead: RegisterableTool = { name: "alza_mobile_read", register(server, wrap) {
    server.registerTool("alza_mobile_read", { title: "Read Alza mobile API data", description: "Read a fixed, APK-confirmed mobile API capability. This tool does not accept arbitrary URLs or credentials.", inputSchema: { operation: z.enum(["url_info", "legacy_product", "router_product", "quick_order_summary", "user_review", "discussion_posts", "premium_trial", "validate_login_name", "o3_info", "validate_isic", "order_helpdesk_questions", "user_data", "contacts", "visitor_navigation", "user_navigation", "catalog_user_navigation", "anonymous_orders", "anonymous_order", "user_order", "order_part", "after_order_payments", "order_add_info", "order2_info", "delivery_countries", "commodity_lists", "commodity_list", "alternatives", "branches", "zip_codes", "search", "category", "facets", "ean_lookup", "hierarchical_filter", "basket_info", "cart", "cost_estimate"]), args: jsonObject.optional() }, annotations: { readOnlyHint: true, idempotentHint: true } }, async (args) => wrap("alza_mobile_read", async () => result(await apiAccount(deps).read(args.operation, args.args ?? {}))));
  }};
  const prepareMutation: RegisterableTool = { name: "alza_prepare_mutation", register(server, wrap) {
    server.registerTool("alza_prepare_mutation", { title: "Prepare an Alza mutation", description: "Create a one-time confirmation token for a fixed, source-confirmed mutation. No request is sent. Low-risk actions (create/rename/delete/add/remove/move/set_country/set_isic/add_gift/add_order_service/set_watchdog/send_feedback/submit_discussion/rate_discussion/coupon_add/coupon_remove/basket_update/basket_unlock) run via alza_mutate_list; high-impact actions (after_order_payment, register, address_*, review_submit, subscription_*, attachment_upload, web_place_order, web_after_order_payment) run via the matching typed tool.", inputSchema: { action: z.enum(["create", "rename", "delete", "add", "remove", "move", "set_country", "set_isic", "add_gift", "add_order_service", "set_watchdog", "send_feedback", "submit_discussion", "rate_discussion", "coupon_add", "coupon_remove", "basket_update", "basket_unlock", "after_order_payment", "register", "address_create", "address_edit", "address_delete", "review_submit", "subscription_activate", "subscription_update_installment", "attachment_upload"]) }, annotations: { readOnlyHint: true, idempotentHint: false } }, async (args) => wrap("alza_prepare_mutation", async () => result(apiAccount(deps).prepareMutation(args.action))));
  }};
  const mutateList: RegisterableTool = { name: "alza_mutate_list", register(server, wrap) {
    server.registerTool("alza_mutate_list", { title: "Execute a whitelisted Alza mutation", description: "Execute one APK-confirmed low-risk mutation (shopping lists, country/ISIC, gift, order service, watchdog, feedback, discussion, coupons, basket update/unlock) using a one-time token from alza_prepare_mutation. Payload fields must match the selected mobile DTO (e.g. coupon_add/coupon_remove take {coupon}; basket_update takes {basket_id, flag?, is_delayed_payment?}). High-impact mutations use their typed tool instead.", inputSchema: { action: z.enum(["create", "rename", "delete", "add", "remove", "move", "set_country", "set_isic", "add_gift", "add_order_service", "set_watchdog", "send_feedback", "submit_discussion", "rate_discussion", "coupon_add", "coupon_remove", "basket_update", "basket_unlock"]), confirmation_token: z.string().min(32), payload: jsonObject }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_mutate_list", async () => result(await apiAccount(deps).mutateList(args.action, args.confirmation_token, args.payload))));
  }};
  const status: RegisterableTool = { name: "alza_account_status", register(server, wrap) {
    server.registerTool("alza_account_status", { title: "Check mobile API auth status", description: "Report whether an access token is loaded in this MCP process.", inputSchema: {}, annotations: { readOnlyHint: true, idempotentHint: true } }, async () => wrap("alza_account_status", async () => result(apiAccount(deps).status())));
  }};
  const cart: RegisterableTool = { name: "alza_cart", register(server, wrap) {
    server.registerTool("alza_cart", { title: "Read Alza cart via mobile API", description: "Read basketInfo and gridOrder1 through the Alza mobile REST API.", inputSchema: {}, annotations: { readOnlyHint: true, idempotentHint: true } }, async () => wrap("alza_cart", async () => result(await apiAccount(deps).cart())));
  }};
  const add: RegisterableTool = { name: "alza_add_to_cart", register(server, wrap) {
    server.registerTool("alza_add_to_cart", { title: "Add product through mobile API", description: "POST a BuyByCode-compatible payload to the mobile basket endpoint.", inputSchema: { code: z.string().min(1), quantity: z.number().int().min(1).max(99).default(1) }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_add_to_cart", async () => result(await apiAccount(deps).addToCart(args.code, args.quantity))));
  }};
  const delivery: RegisterableTool = { name: "alza_delivery_options", register(server, wrap) {
    server.registerTool("alza_delivery_options", { title: "List mobile API delivery options", description: "Call the APK-confirmed getDeliveryPaymentGroups endpoint. Pass selected_delivery_option_id when the API requires a selected delivery method.", inputSchema: { selected_delivery_option_id: z.number().int().optional() }, annotations: { readOnlyHint: true, idempotentHint: true } }, async (args) => wrap("alza_delivery_options", async () => result(await apiAccount(deps).deliveryOptions(args.selected_delivery_option_id))));
  }};
  const pickup: RegisterableTool = { name: "alza_select_pickup_point", register(server, wrap) {
    server.registerTool("alza_select_pickup_point", { title: "Select AlzaBox through mobile API", description: "POST the APK's DeliveryPaymentAssociation payload to getDeliveryAssociations. The payload must be taken from the current mobile API delivery response; this tool never submits a browser form.", inputSchema: { association: jsonObject }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_select_pickup_point", async () => result(await apiAccount(deps).selectAlzaBox(args.association))));
  }};
  const preview: RegisterableTool = { name: "alza_checkout_preview", register(server, wrap) {
    server.registerTool("alza_checkout_preview", { title: "Preview mobile API checkout", description: "Run the APK-confirmed sendOrder1 and delivery-payment-group reads. This never submits an order and returns a one-time confirmation token.", inputSchema: { selected_delivery_option_id: z.number().int().optional() }, annotations: { readOnlyHint: true, idempotentHint: false } }, async (args) => wrap("alza_checkout_preview", async () => result(await apiAccount(deps).previewOrder(args.selected_delivery_option_id))));
  }};
  const place: RegisterableTool = { name: "alza_place_order", register(server, wrap) {
    server.registerTool("alza_place_order", { title: "Submit mobile API order", description: "Execute the APK-confirmed multi-step order sequence only with a checkout preview token and explicit JSON payloads for SelectedDeliveryPayment, SendOrderUserInfo, and SendCompleteOrder. No browser form is used.", inputSchema: { confirmation_token: z.string().min(32), delivery_payment: jsonObject, user_info: jsonObject, complete_order: jsonObject }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_place_order", async () => result(await apiAccount(deps).submitOrder(args.confirmation_token, args.delivery_payment, args.user_info, args.complete_order))));
  }};
  const webPickupPlaces: RegisterableTool = { name: "alza_web_pickup_places", register(server, wrap) {
    server.registerTool("alza_web_pickup_places", { title: "List web pickup places (AlzaBox, branches, 24/7)", description: "Read the live m.alza.cz pickup family (personalPickup/v1): type-availability form (AlzaBox/branches/24-7/showroom counts), the paginated place list, and an optional single-place detail (deliveryId, parcelShopId, isFree, typeText, opening hours). Use order_id/group_id from the current basket checkout context. Read-only, no token. Use the returned deliveryId/parcelShopId with alza_web_place_order.", inputSchema: { order_id: z.number().int().positive().optional().describe("Basket/order id of the current checkout (from the basket context)."), group_id: z.number().int().positive().optional().describe("Delivery group id (from delivery options)."), latitude: z.number().min(-90).max(90).optional(), longitude: z.number().min(-180).max(180).optional(), types: z.array(z.number().int().positive()).min(1).max(5).optional().describe("Pickup type filter (e.g. 1=AlzaBox, 2=branches); omit for all types."), limit: z.number().int().min(1).max(100).optional(), offset: z.number().int().min(0).optional(), place_id: z.number().int().positive().optional().describe("Fetch the detail for a single place (the call the web UI fires on place selection).") }, annotations: { readOnlyHint: true, idempotentHint: true } }, async (args) => wrap("alza_web_pickup_places", async () => result(await apiAccount(deps).webPickupPlaces(args))));
  }};
  return [authDiscovery, authStart, authExchange, mobileRead, prepareMutation, mutateList, status, cart, add, delivery, pickup, preview, place, webPickupPlaces];
}
