import { z } from "zod";
import type { MobileAccount } from "../domain/mobile-account.js";
import type { RegisterableTool, ToolDeps, ToolResult } from "./types.js";

function apiAccount(deps: ToolDeps): MobileAccount {
  if (!deps.mobileAccount) throw new Error("mobile API account tools are not configured");
  return deps.mobileAccount;
}
function result(value: unknown): ToolResult {
  return { content: [{ type: "text", text: JSON.stringify(value, null, 2) }], structuredContent: value as Record<string, unknown> };
}
const jsonObject = z.record(z.string(), z.unknown());
const typedValues = z.array(z.object({
  name: z.string().min(1).max(64),
  value: z.unknown(),
  kind: z.enum(["text", "integer", "boolean", "decimal", "text-array", "integer-array"]).optional(),
})).max(20);
const appAction = jsonObject.describe("An AppAction object copied from the response of a prior alza tool (e.g. alza_profile); it must contain form.meta.href. Never hand-crafted URLs.");
const confirmationToken = z.string().min(32).describe("One-time token from alza_prepare_mutation for the matching action.");

export function createAdvancedTools(deps: ToolDeps): RegisterableTool[] {
  const profile: RegisterableTool = { name: "alza_profile", register(server, wrap) {
    server.registerTool("alza_profile", { title: "Read Alza user profile and address book", description: "Read the authenticated user data (APK getUserData endpoint): personal data, address book with per-address actions, and account sections. Read-only. Requires OAuth exchange first.", inputSchema: {}, annotations: { readOnlyHint: true, idempotentHint: true } }, async () => wrap("alza_profile", async () => result(await apiAccount(deps).profile())));
  }};
  const contacts: RegisterableTool = { name: "alza_contacts", register(server, wrap) {
    server.registerTool("alza_contacts", { title: "Read Alza account contacts", description: "Read the authenticated user's contact list (APK-confirmed v4/contacts endpoint). Read-only.", inputSchema: {}, annotations: { readOnlyHint: true, idempotentHint: true } }, async () => wrap("alza_contacts", async () => result(await apiAccount(deps).contacts())));
  }};
  const register: RegisterableTool = { name: "alza_register", register(server, wrap) {
    server.registerTool("alza_register", { title: "Register a new Alza account", description: "Submit the APK-confirmed CreateUser registration (Register DTO: email, phone, pwd, optional verification code). Credential-bearing and high-impact: requires a one-time token from alza_prepare_mutation (action=register) and explicit user confirmation.", inputSchema: { email: z.string().min(3).max(100), phone: z.string().min(6).max(20), pwd: z.string().min(8).max(64), code: z.string().max(32).optional(), confirmation_token: confirmationToken }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_register", async () => result(await apiAccount(deps).register({ email: args.email, phone: args.phone, pwd: args.pwd, code: args.code }, args.confirmation_token))));
  }};
  const addressUpsert: RegisterableTool = { name: "alza_address_upsert", register(server, wrap) {
    server.registerTool("alza_address_upsert", { title: "Create or edit a delivery address", description: "Execute the server-provided address form action (from alza_profile: createAddressAction for create, per-address editAction for edit) with typed address fields. Mutating: requires a one-time token from alza_prepare_mutation (action=address_create or address_edit).", inputSchema: z.object({ kind: z.enum(["create", "edit"]), action: appAction, name: z.string().min(1).max(100), street: z.string().min(1).max(100), city: z.string().min(1).max(100), zip_code: z.string().min(3).max(10), firm: z.string().max(100).optional(), phone: z.string().min(6).max(20).optional(), email: z.string().max(100).optional(), note: z.string().max(100).optional(), address_type: z.enum(["HOME", "WORK", "OTHER"]).optional(), address_id: z.number().int().positive().optional().describe("Required for kind=edit."), confirmation_token: confirmationToken }).superRefine((v, ctx) => { if (v.kind === "edit" && v.address_id === undefined) ctx.addIssue({ code: z.ZodIssueCode.custom, message: "address_id is required when kind=edit", path: ["address_id"] }); }), annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_address_upsert", async () => result(await apiAccount(deps).addressUpsert(args.kind, args.action, { name: args.name, street: args.street, city: args.city, zip_code: args.zip_code, firm: args.firm, phone: args.phone, email: args.email, note: args.note, address_type: args.address_type, address_id: args.address_id }, args.confirmation_token))));
  }};
  const addressDelete: RegisterableTool = { name: "alza_address_delete", register(server, wrap) {
    server.registerTool("alza_address_delete", { title: "Delete a delivery address", description: "Execute the per-address delete action from the alza_profile response. Mutating: requires a one-time token from alza_prepare_mutation (action=address_delete).", inputSchema: { action: appAction, address_id: z.number().int().positive(), confirmation_token: confirmationToken }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_address_delete", async () => result(await apiAccount(deps).addressDelete(args.action, { address_id: args.address_id }, args.confirmation_token))));
  }};
  const addressSearch: RegisterableTool = { name: "alza_address_search", register(server, wrap) {
    server.registerTool("alza_address_search", { title: "Search delivery addresses", description: "Follow the server-provided address search action (addressSearchAction from alza_profile) with a zip/city query. Read-only, no token required.", inputSchema: { action: appAction, query: z.string().min(1).max(50) }, annotations: { readOnlyHint: true, idempotentHint: true } }, async (args) => wrap("alza_address_search", async () => result(await apiAccount(deps).addressSearch(args.action, args.query))));
  }};
  const paymentMethods: RegisterableTool = { name: "alza_payment_methods", register(server, wrap) {
    server.registerTool("alza_payment_methods", { title: "List available payment methods", description: "Read the payment-method groups from the APK-confirmed getDeliveryPaymentGroups endpoint (payment projection). Requires a cart with products. Read-only.", inputSchema: { selected_delivery_option_id: z.number().int().positive().optional() }, annotations: { readOnlyHint: true, idempotentHint: true } }, async (args) => wrap("alza_payment_methods", async () => result(await apiAccount(deps).paymentMethods(args.selected_delivery_option_id))));
  }};
  const afterOrderPayments: RegisterableTool = { name: "alza_after_order_payments", register(server, wrap) {
    server.registerTool("alza_after_order_payments", { title: "List after-order payment options", description: "Read the available after-order payment methods/options for an order part (APK-confirmed getafterorderpayments endpoint). Read-only. Use the returned payment id with alza_pay_after_order.", inputSchema: { order_id: z.string().min(1).max(64), part_id: z.string().min(1).max(64) }, annotations: { readOnlyHint: true, idempotentHint: true } }, async (args) => wrap("alza_after_order_payments", async () => result(await apiAccount(deps).afterOrderPayments(args.order_id, args.part_id))));
  }};
  const payAfterOrder: RegisterableTool = { name: "alza_pay_after_order", register(server, wrap) {
    server.registerTool("alza_pay_after_order", { title: "Execute an after-order payment", description: "Submit the APK-confirmed afterOrderPayment (AfterOrderRequestBody: order id, invoice number, payment id from alza_after_order_payments, optional stored-card id and device fingerprint). Money movement, high-impact: requires a one-time token from alza_prepare_mutation (action=after_order_payment) and explicit user confirmation.", inputSchema: { order_id: z.string().min(1).max(64), invoice_number: z.string().min(1).max(64), payment_id: z.number().int().positive(), card_id: z.number().int().positive().optional(), device_fingerprint: z.string().max(128).optional(), confirmation_token: confirmationToken }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_pay_after_order", async () => result(await apiAccount(deps).payAfterOrder({ order_id: args.order_id, invoice_number: args.invoice_number, payment_id: args.payment_id, card_id: args.card_id, device_fingerprint: args.device_fingerprint }, args.confirmation_token))));
  }};
  const order: RegisterableTool = { name: "alza_order", register(server, wrap) {
    server.registerTool("alza_order", { title: "Read an Alza order and its part", description: "Read an authenticated user order (APK-confirmed user order endpoint; includes parts, milestones/tracking, and invoice document references) plus an optional part detail read. Read-only. user_flag 0/1 selects the order scope exactly as the APK does.", inputSchema: { order_id: z.string().min(1).max(64), part_id: z.string().min(1).max(64).optional(), user_flag: z.union([z.literal(0), z.literal(1)]).default(0), initial_created: z.boolean().default(false) }, annotations: { readOnlyHint: true, idempotentHint: true } }, async (args) => wrap("alza_order", async () => result(await apiAccount(deps).order(args.order_id, args.part_id, args.user_flag, args.initial_created))));
  }};
  const reviewSubmit: RegisterableTool = { name: "alza_review_submit", register(server, wrap) {
    server.registerTool("alza_review_submit", { title: "Submit a product review", description: "Submit the server-provided review form action (writeReviewAction/onSubmitReview or rating form from the product detail) with a 1-5 rating and optional text. Mutating: requires a one-time token from alza_prepare_mutation (action=review_submit).", inputSchema: { action: appAction, rating: z.number().int().min(1).max(5), text: z.string().max(10000).optional(), values: typedValues.optional().describe("Extra typed form values from the product-detail form response."), confirmation_token: confirmationToken }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_review_submit", async () => result(await apiAccount(deps).reviewSubmit(args.action, { rating: args.rating, text: args.text, values: args.values }, args.confirmation_token))));
  }};
  const complaintClaims: RegisterableTool = { name: "alza_complaint_claims", register(server, wrap) {
    server.registerTool("alza_complaint_claims", { title: "List warranty claims", description: "Follow the server-provided warranty-claims action (activeWarrantyClaimsAction / showActiveWarrantyClaimsAction from authenticated navigation or order detail) to read the claim list. Read-only.", inputSchema: { action: appAction }, annotations: { readOnlyHint: true, idempotentHint: true } }, async (args) => wrap("alza_complaint_claims", async () => result(await apiAccount(deps).complaintClaims(args.action))));
  }};
  const subscriptionOverview: RegisterableTool = { name: "alza_subscription_overview", register(server, wrap) {
    server.registerTool("alza_subscription_overview", { title: "Read AlzaSubscription overview", description: "Follow the server-provided subscription action (subscriptionAction / AlzaSubscriptionOverview action from account menu or authenticated navigation) to read subscription phases, savings, and trial settings. Read-only.", inputSchema: { action: appAction }, annotations: { readOnlyHint: true, idempotentHint: true } }, async (args) => wrap("alza_subscription_overview", async () => result(await apiAccount(deps).subscriptionOverview(args.action))));
  }};
  const subscriptionActivate: RegisterableTool = { name: "alza_subscription_activate", register(server, wrap) {
    server.registerTool("alza_subscription_activate", { title: "Activate AlzaSubscription", description: "Execute the server-provided subscription activation action (activateAction form). High-impact: starts a paid subscription; requires a one-time token from alza_prepare_mutation (action=subscription_activate).", inputSchema: { action: appAction, values: typedValues.optional().describe("Extra typed form values (e.g. payment/installment fields) from the subscription form response."), confirmation_token: confirmationToken }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_subscription_activate", async () => result(await apiAccount(deps).subscriptionActivate(args.action, { values: args.values }, args.confirmation_token))));
  }};
  const subscriptionUpdateInstallment: RegisterableTool = { name: "alza_subscription_update_installment", register(server, wrap) {
    server.registerTool("alza_subscription_update_installment", { title: "Update AlzaSubscription installment plan", description: "Execute the server-provided installment-update action (updateInstallmentAction form). High-impact: changes the payment schedule; requires a one-time token from alza_prepare_mutation (action=subscription_update_installment).", inputSchema: { action: appAction, values: typedValues.optional().describe("Extra typed form values (installment fields) from the subscription form response."), confirmation_token: confirmationToken }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_subscription_update_installment", async () => result(await apiAccount(deps).subscriptionUpdateInstallment(args.action, { values: args.values }, args.confirmation_token))));
  }};
  const webPlaceOrder: RegisterableTool = { name: "alza_web_place_order", register(server, wrap) {
    server.registerTool("alza_web_place_order", { title: "Place an order through the legacy web WCF checkout pipeline", description: "Execute the live-verified EShopService.svc chain (SaveOrder2 → SaveOrder3 → SaveAndConfirmOrder2, with the documented AlzaPlus 113-gate retry → CheckOrder4 → SendOrder4). This is the working order-submission path while the mobile sendOrder3 endpoint 500s (see docs/gap-analysis.md G1/G5). Typed inputs only; the delivery group/delivery/parcel-shop come from alza_delivery_options and alza_web_pickup_places, the payment id from alza_payment_methods. High-impact (creates a real order): requires a one-time token from alza_prepare_mutation (action=web_place_order).", inputSchema: { delivery_id: z.number().int().positive().describe("Delivery option id (e.g. 2680 for AlzaBox; from delivery options)."), delivery_group_id: z.number().int().min(0).optional().describe("Live delivery group id (from delivery options; omit or 0 for the server default)."), parcel_shop_id: z.string().max(32).optional().describe("Pickup place id (e.g. an AlzaBox parcelShopId from alza_web_pickup_places)."), payment_id: z.number().int().positive().describe("Payment method id (e.g. 103 proforma; from payment methods)."), name: z.string().min(1).max(100), street: z.string().min(1).max(100), city: z.string().min(1).max(100), zip_code: z.string().min(3).max(12), phone: z.string().min(6).max(20), email: z.string().min(3).max(100), register_user: z.boolean().default(false), login: z.string().max(100).optional().describe("Existing login (defaults to the email)."), country_id: z.number().int().default(0), quotation: z.boolean().default(false), internal_description: z.string().max(2000).optional(), user_consents: z.array(z.object({ consent_id: z.string().min(1).max(64), value: z.boolean() })).max(10).optional(), basket_consents: z.array(z.object({ consent_id: z.string().min(1).max(64), value: z.boolean() })).max(10).optional(), confirmation_token: confirmationToken }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_web_place_order", async () => result(await apiAccount(deps).webPlaceOrder({ delivery_id: args.delivery_id, delivery_group_id: args.delivery_group_id, parcel_shop_id: args.parcel_shop_id, payment_id: args.payment_id, name: args.name, street: args.street, city: args.city, zip_code: args.zip_code, phone: args.phone, email: args.email, register_user: args.register_user, login: args.login, country_id: args.country_id, quotation: args.quotation, internal_description: args.internal_description, user_consents: args.user_consents, basket_consents: args.basket_consents }, args.confirmation_token))));
  }};
  const webPayAfterOrder: RegisterableTool = { name: "alza_web_pay_after_order", register(server, wrap) {
    server.registerTool("alza_web_pay_after_order", { title: "Execute a web after-order payment (legacy WCF CreateAfterPayment)", description: "Initiate the after-order payment for an unpaid order through the live-verified EShopService.svc CreateAfterPayment chain (the recorded real-payment path: e.g. MojePlatba 144 → KB SSO gateway). List the available payment ids first via alza_mobile_read operation=web_after_payment_dialog (GetAfterPaymentDialog). Money movement, high-impact: requires a one-time token from alza_prepare_mutation (action=web_after_order_payment).", inputSchema: { order_id: z.string().min(1).max(64), payment_id: z.number().int().positive().describe("Payment method id from the after-payment dialog (e.g. 144 MojePlatba, 143 Platba 24, 103 proforma)."), order_hash: z.string().max(64).optional().describe("The ?x= order hash (from the order-detail link)."), invoice_id: z.string().max(32).optional().default("0"), price: z.number().min(0).optional().describe("Override the amount to pay (defaults to the full due amount)."), confirmation_token: confirmationToken }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_web_pay_after_order", async () => result(await apiAccount(deps).webAfterOrderPayment({ order_id: args.order_id, payment_id: args.payment_id, order_hash: args.order_hash, invoice_id: args.invoice_id, price: args.price }, args.confirmation_token))));
  }};
  const uploadAttachment: RegisterableTool = { name: "alza_upload_attachment", register(server, wrap) {
    server.registerTool("alza_upload_attachment", { title: "Upload complaint/claim attachments", description: "Upload image attachments through the server-provided multipart action (uploadImageAction / complaint attachment actions). Accepts 1-5 base64 data-URL files with whitelisted image MIME types (max 10 MiB each). Mutating: requires a one-time token from alza_prepare_mutation (action=attachment_upload).", inputSchema: { action: appAction, files: z.array(z.object({ part_name: z.string().min(1).max(64), file_name: z.string().min(1).max(200), mime_type: z.string().max(64).optional(), data_url: z.string().startsWith("data:") })).min(1).max(5), values: typedValues.optional(), confirmation_token: confirmationToken }, annotations: { readOnlyHint: false, idempotentHint: false } }, async (args) => wrap("alza_upload_attachment", async () => result(await apiAccount(deps).uploadAttachment(args.action, { files: args.files, values: args.values }, args.confirmation_token))));
  }};
  return [profile, contacts, register, addressUpsert, addressDelete, addressSearch, paymentMethods, afterOrderPayments, payAfterOrder, webPayAfterOrder, order, reviewSubmit, complaintClaims, subscriptionOverview, subscriptionActivate, subscriptionUpdateInstallment, uploadAttachment, webPlaceOrder];
}
